[pytest]
pythonpath = .
testpaths = tests
addopts = -ra --strict-markers --strict-config --cov=. --cov-report=term-missing --cov-report=xml:coverage.xml
filterwarnings =
    ignore::DeprecationWarning
