sonar.projectKey=huytran2005_s2o-api
sonar.organization=huytran2005
sonar.host.url=https://sonarcloud.io
sonar.projectName=s2o-api
sonar.projectVersion=1.0

sonar.sources=controllers,db,models,schemas,utils,main.py
sonar.tests=tests
sonar.test.inclusions=tests/**/*.py
sonar.python.coverage.reportPaths=coverage.xml

sonar.exclusions=**/__pycache__/**,**/.pytest_cache/**,**/.ruff_cache/**,**/.scannerwork/**,**/.venv/**,alembic/**,media/**,test/**,tests/**,**/*.pyc
sonar.coverage.exclusions=alembic/**,media/**,test/**,tests/**,**/__init__.py
