name: Deploy to Render

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Render Deploy
        run: curl -X POST "https://api.render.com/deploy/srv-d7fg15a8qa3s73dib4bg?key=z2CxiICrqh8"